#include <iostream.h>
#include <graphics.h>
#include <iomanip.h>
#include <fstream.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include <stdio.h>
#include <dos.h>
#include <process.h>
#include <ctype.h>
#include <math.h>
 


void ABTUS()
  {
  clrscr();
  char op;
  cout<<"\n\n**********************************************************************";
  cout<<"\n\n\t\t\tABOUT US! \1";
  cout<<"\n\t\t\t-------------";
  cout<<"\n\n\t\t RAINBOW TRAVELS...We add colours to your journey!.";
   cout<<"\n\n\t Rainbow travels has been rendering excellent services"<<endl;
  cout<<"\n\n\t by Miss. Ankitha Nandanavanam and"<<endl;
  cout<<"\n\n\t Miss. Sanjana Rao. It is a great pleasure for us to serve"<<endl;
  cout<<"\n\n\t our customers with our experienced travel executives."<<endl;
  cout<<"\n\n**********************************************************************";
  cout<<"\n\n\t READ MORE.....? ";
   cin>>op;
  if(op=='Y' || op=='y')
  {
  clrscr();
  cout<<"\n\n*****************************************************************************";
  cout<<"\n\t\t Rainbow travels has been rendering excellent services"<<endl;
  cout<<"\n\t Miss. Ankitha Nandanavanam and"<<endl;
  cout<<"\n\t Miss. Sanjana Rao. It is a great pleasure for us to serve"<<endl;
  cout<<"\n\t our customers with our experienced travel executives."<<endl;
  cout<<"\n\t\tThe care and honest service of our well experienced staff"<<endl;
  cout<<"\n\t make your holiday most enjoyable and comfortable.So,let's"<<endl;
  cout<<"\n\t share a memorable holiday together!Along with our travels,we"<<endl;
  cout<<"\n\t also have experiences in conferance hall bookings."<<endl;
  cout<<"\n\t\tWe would be delighted to send you the required information"<<endl;
  cout<<"\n\t with our suggestions because we believe in good service,value,"<<endl;
  cout<<"\n\t and word of mouth to keep clients coming back to us. "<<endl;
  cout<<"\n\t Contact Deatils: www.rainbowww_tr.in, Cnct. no.: (034)2534678."<<endl;
  cout<<"\n*****************************************************************************";
  }
  getch();
  }
